<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Thin wrapper around PHP's native password_hash/password_verify.
 * Uses bcrypt at cost 12, matching the original bcryptjs.hash(plain, 12)
 * call in lib/auth.ts — so hashes generated by either implementation are
 * verifiable by the other (both are standard bcrypt).
 */
final class Password
{
    private const COST = 12;

    public static function hash(string $plain): string
    {
        return password_hash($plain, PASSWORD_BCRYPT, ['cost' => self::COST]);
    }

    public static function verify(string $plain, string $hash): bool
    {
        return password_verify($plain, $hash);
    }
}
